aqq/aqq/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
]

aqq/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aqq/',include('myapp.urls',namespace='aqq')),

]

myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'aqq'
urlpatterns = [
    path('account/', my_account,name='account'),
    path('enroll/', register, name='enroll'),
    path('home/',go_index,name='home'),
    path('details/<id>/',go_details,name = 'details'),
    path('center/',press_center,name='center'),
    path('invest/<tid>/<sid>/<did>/<page>/',invest,name= 'invest'),
    path('product/<pid>/',details,name='product'),
    path('borrow/',borrow_money,name='borrow'),
    path('secure/',secure,name='secure'),
    path('anenst/',anenst,name='anenst'),
    path('guide/',guide,name='guide'),
    path('help/',help,name='help'),
    path('recharge/',recharge,name='recharge'),
    path('withdraw/',withdraw,name='withdraw'),
    path('login/',login,name='login'),
    path('register/',register,name='register'),
    path('getcode/<phone>/',codes,name='codes'),
    path('pledge/',pledge,name='pledge'),
    path('mortgage/',mortgage,name='mortgage'),
    path('venture/',venture,name='venture'),
    path('policy/',policy,name='policy'),
    path('logout/',logout,name='logout'),
    path('buy_success/',buy_success,name='buy_success'),
    path('buy/<pid>/',buy,name='buy'),
<<<<<<< HEAD
    path('myinvestment/',my_investment,name='myinvestment')
=======
    path('financing/',financing,name='financing')
>>>>>>> df4b583288f1fef117b54b3e1bfa9b63ba88f278


]

templates/enroll-3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册账户-身份验证</title>
    <!--公共样式-->
    <link rel="stylesheet" href="/static/css/global.css">
    <link rel="stylesheet" href="/static/css/enroll.css">
    <link rel="stylesheet" type="text/css" href="/static/css/hzw-city-picker.css">
    <script src="/static/js/jquery-1.8.2.js"></script>
    <script type="text/javascript" src="/static/js/city-data.js"></script>
    <script type="text/javascript" src="/static/js/hzw-city-picker.min.js"></script>
    <!--公共js-->
    <script src="/static/js/common.js"></script>
</head>
<body>
<!--head开始-->
<div class="head">
    <!--顶头-->
    <div class="top-head">
        <div class="top-menu">
            <!--左边-->
            <div class="top-left">
                <p>客服热线: &nbsp;400-050-3015</p>
                <!--微信二维码-->
                <div class="mobile">
                    <p class="icc" id="wechat">
                        <i class="Wechat"></i>微信
                    </p>
                    <!--二维码-->
                    <div class="wecgat-rq">
                    </div>
                </div>
                <!--QQ客服-->
                <p class="icc"><a href="javascript:;" target="_blank"><i class="QQ"></i>客服</a></p>

            </div>
            <!--右边-->
            <div class="top-right">
                <a target="_blank" href="javascript:;" class="red">快速注册</a>
                <a target="_blank" href="login.html">立即登录</a>
                <a target="_blank" href="{% url 'aqq:help' %}">帮助中心</a>
            </div>
        </div>
    </div>
    <!--LOGO及导航-->
    <div class="top-nav">
        <a href="index.html"><div class="logo"></div></a>
        <div class="nav-list">
            <ul>
                <li><a target="_blank" href="{% url 'aqq:home' %}">首页</a></li>
                <li><a target="_blank" href="{% url 'aqq:invest' tid=0 sid=0 did=0 page=1 %}">投资理财</a></li>
                <li><a target="_blank" href="{% url 'aqq:borrow' %}" class="red">借贷专区</a></li>
                <li><a target="_blank" href="{% url 'aqq:secure' %}">安全保障</a></li>
                <li><a target="_blank" href="{% url 'aqq:anenst' %}">关于我们</a></li>
                <li><a target="_blank" href="{% url 'aqq:guide' %}">新手引导</a></li>
                <li><a target="_blank" href="{% url 'aqq:account' %}" class="my-cons"><i class="my-con"></i>我的账户</a></li>
            </ul>
        </div>
    </div>

</div>
<!--head结束-->
<div class="bd">
    <!--购买成功-->
    <div class="center">
        <!--流程-->
        <div class="flow">
            <ul>
                <li>
                    <h6 class="flow-h6-2">1</h6>
                    <span>创建账户</span>
                </li>
                <i class="flow-icon-1"></i>
                <li>
                    <h6 class="flow-h6-3">2</h6>
                    <span>身份认证</span>
                </li>
                <i class="flow-icon-2"></i>
                <li>
                    <h6 class="flow-h6-1">3</h6>
                    <span class="red">添加银行卡</span>
                </li>
                <i class="flow-icon-3"></i>
                <li>
                    <h6 class="flow-h6-4"></h6>
                    <span>注册成功</span>
                </li>
            </ul>
        </div>
        <!--表单-->
        <div class="form">
            <form action="enroll-4.html">
                <div class="div-phone">
                    <label for="phone">卡号</label><input type="text" id="phone" class="infos" name="bank_num" placeholder="请输入本人银行卡号" />
                </div>
                <div class="div-ranks">
                    <label for="identity">银行名称</label>
                    <select id="category" name="category" class="banks">
                        <option value="">请选择银行</option>
                        <option value="1">银行1</option>
                        <option value="2">银行2</option>
                        <option value="3">银行3</option>
                        <option value="4">银行4</option>
                    </select>
                </div>
                <div class="div-ranks">
                    <label for="identity">所在地</label><input type="text" class="infos" id="cityChoice" name="city" placeholder="请选择你的城市" >
                </div>

                <div class="div-ranks">
                    <label for="identity">开户行</label><input type="text" id="identity" class="infos" name="open_bank" placeholder="请输入开户行"  />
                </div>

                <div class="div-pho">
                    <label for="tel">手机号码</label><input type="text" id="tel" class="infos" name="phone" placeholder="请输入本人手机号" />
                </div>
                <div class="div-conform">
                    <a href="javascript:;" class="conform" id="submit">下一步</a>
                </div>
            </form>
            <div class="hint">
                <h3 class="red">温馨提示</h3>
                <p>须填写本人名下的“手机号”及“银行卡号”请认真核对后再确认。</p>
            </div>
        </div>
        <!--表单end-->

    </div>
</div>

<!--底部-->
<div class="foot">
    <div class="foot-center">
        <h2>注册典贷通，开启理财、贷款新旅程</h2>
        <ul>
            <li><i class="foot-icon-1"></i>利息按天返</li>
            <li><i class="foot-icon-2"></i>0元手续费</li>
            <li><i class="foot-icon-3"></i>100元起投</li>
            <li><i class="foot-icon-4"></i>100%本息保障</li>
        </ul>
    </div>
</div>

</body>
<script>

   $(function () {
       $('#category option[value=" "]').attr('selected',true);

       var cityPicker = new HzwCityPicker({
           data: data,
           target: 'cityChoice',
           valType: 'k-v',
           hideCityInput: {
               name: 'city',
               id: 'city'
           },
           hideProvinceInput: {
               name: 'province',
               id: 'province'
           },
           callback: function(){
//               alert('OK');
           }
       });

       cityPicker.init();

       $('#submit').on('click', function() {
               $('form').submit();
       });
   })
</script>
</html>

templates/my-recharge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的账户-充值</title>
    <!--公共样式-->
    <link rel="stylesheet" href="/static/css/global.css">
    <link rel="stylesheet" href="/static/css/my-account.css">
    <script src="/static/js/jquery-1.8.2.js"></script>

    <!--公共js-->
    <script src="/static/js/common.js"></script>
    <script src="/static/js/my-account.js"></script>
</head>
<body>
<!--head开始-->
<div class="head">
    <!--顶头-->
    <div class="top-head">
        <div class="top-menu">
            <!--左边-->
            <div class="top-left">
                <p>客服热线: &nbsp;400-050-3015</p>
                <!--微信二维码-->
                <div class="mobile">
                    <p class="icc" id="wechat">
                        <i class="Wechat"></i>微信
                    </p>
                    <!--二维码-->
                    <div class="wecgat-rq">
                    </div>
                </div>
                <!--QQ客服-->
                <p class="icc"><a href="javascript:;" target="_blank"><i class="QQ"></i>客服</a></p>

            </div>
            <!--右边-->
            {% if user %}
            <div class="top-right">
                <a target="_blank" href="{% url 'aqq:account' %}">您好！{{ user.name }}</a>
                <a target="_blank" href="{% url 'aqq:logout' %}">退出</a>
                <a target="_blank" href="help-center.html">帮助中心</a>
            </div>
            {% else %}
                <div class="top-right">
                <a target="_blank" href="{% url 'aqq:enroll' %}">快速注册</a>
                <a target="_blank" href="{% url 'aqq:login' %}">立即登录</a>
                <a target="_blank" href="help-center.html">帮助中心</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!--LOGO及导航-->
    <div class="top-nav">
        <a href="index.html"><div class="logo"></div></a>
        <div class="nav-list">
            <ul>
               <li><a target="_blank" href="{% url 'aqq:home' %}">首页</a></li>
                <li><a target="_blank" href="{% url 'aqq:invest' tid=0 sid=0 did=0 page=1 %}">投资理财</a></li>
                <li><a target="_blank" href="{% url 'aqq:borrow' %}" class="red">借贷专区</a></li>
                <li><a target="_blank" href="{% url 'aqq:secure' %}">安全保障</a></li>
                <li><a target="_blank" href="{% url 'aqq:anenst' %}">关于我们</a></li>
                <li><a target="_blank" href="{% url 'aqq:guide' %}">新手引导</a></li>
                <li><a target="_blank" href="{% url 'aqq:account' %}" class="my-cons"><i class="my-con"></i>我的账户</a></li>
            </ul>
        </div>
    </div>

</div>
<!--head结束-->
<div class="bd clearfix">
    <div class="kong"></div>
    <!---->
    <!--面包屑导航-->
    <div class="crumbs" style="background-color:#f3f3f3">
        <span><a href="javascript:;" title="当前位置">当前位置：</a></span>
        <span><a href="{% url 'aqq:home' %}" target="_blank" title="首页">首页</a>&nbsp;&gt;&nbsp;</span>
        <span><a href="{% url 'aqq:account' %}" style="color: #F3270D" target="_blank" title="我的账户">我的账户</a></span>

    </div>
    <div class="center">
        <!--左侧导航-->
        <div class="nav-left">
            <ul class="my-list">
                <li class="my-own nav-one"><i class="accicon-l-1"></i><a href="{% url 'aqq:home' %}">账户首页</a></li>
                <li class="my-own my-fund-1"><i class="accicon-l-2"></i>我的资金 <i class="accicon-r-1"></i></li>
                <div class="my-rec-1">
                    <ul>
                        <li><a href="{% url 'aqq:recharge' %}" class="red">充值</a></li>
                        <li><a href="{% url 'aqq:withdraw' %}">提现</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-2"><i class="accicon-l-3"></i>我的投资 <i class="accicon-r-2"></i></li>
                <div class="my-rec-2">
                    <ul>
                        <li><a href="my-investment.html">投资记录</a></li>
                        <li><a href="my-financing.html">资金记录</a></li>
                        <li><a href="my-drawmoney.html">提现记录</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-3"><i class="accicon-l-4"></i>我的借款 <i class="accicon-r-3"></i></li>
                <div class="my-rec-3">
                    <ul>
                        <li><a href="my-borrowing.html">借款记录</a></li>
                        <li><a href="my-payments.html">回款记录</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-4"><i class="accicon-l-5"></i>个人设置 <i class="accicon-r-4"></i></li>
                <div class="my-rec-4">
                    <ul>
                        <li><a href="my-setdatum.html">基本信息</a></li>
                        <li><a href="my-setsecure.html">安全中心</a></li>
                    </ul>
                </div>
                <li class="my-own"><i class="accicon-l-6"></i> <i class="acc-add"></i><a href="my-invite.html">我的邀请</a></li>
                <li class="my-own"><i class="accicon-l-7"></i><a href="my-brokerage.html">我的佣金</a></li>
            </ul>
        </div>

        <!--右侧内容-->
        <div class="center-box">
            <!--充值-->
            <div class="recharge">
                <div class="recharge-txt">
                    <h3><i class="wjx"></i>
                        温馨提示
                    </h3>
                    <p>1.  典贷通使用第三方支付平台融托富进行资金监管；</p>
                    <p>2.  为了您的账户安全，请在充值前进行实名身份认证、绑卡签约获取交易密码；</p>
                    <p>3.  银行卡必须是本人银行卡且银行预留手机号码要与平台注册手机号码保持一致；</p>
                    <p>4.  支付限额请参照各大银行的限额说明，如有疑问请咨询开户行客服</p>
                    <p> &nbsp; &nbsp; &nbsp;注：“移动支付”支持银行：工、农、中、建、中信、光大、民生、平安、兴业等银行的借记卡，</p>
                    <p> &nbsp; &nbsp; &nbsp;在移动端只需关联银行卡,付款时输入手机校验码即可完成；</p>
                    <p>5.  如果充值资金没有及时到账，请联系在线客服或拨打: 400-050-3015。</p>
                </div>
                <div class="recharge-num">
                    <ul>
                        <li>
                            <span>账户余额 <em>{{ balance }}</em>元</span>
                        </li>
                        <li>
                            <label>充值金额</label>
                            <input type="text" value="" class="infos" name="money" placeholder="请输入充值金额" id="add"/>
                        </li>
                        <li>
                            <button  class="recharge-sub" id="btn">充值</button>
                        </li>
                    </ul>
                </div>

            </div>
            <!--充值成功-->
            <div class="recharge-suss">
                <div class="recharge-prompt">
                    <h3><i></i>充值成功</h3>
                    <span>账户余额 <em id="balance"></em>元</span>
                </div>
            </div>
        </div>

    </div>
</div>
<!--右侧悬浮回到顶部-->
<div class="toolbar" id="rights" style="display: none">
    <a href="javascript:;" class="toolbar-item toolbar-item-weixin">
        <span class="toolbar-layer"></span>
    </a>
    <a href="Feedback.html" class="toolbar-item toolbar-item-feedback"></a>
    <a href="javascript:;" id="returnTop" class="toolbar-item toolbar-item-top"></a>
</div>
<!--footer开始-->
<div class="footer">
    <div class="foo-conter">
        <div class="foo-t">
            <div class="foo-top">
                <div class="foo-one">
                    <ul>
                        <li>
                            <a target="_blank" href="business.html">业务模式</a>
                            <a target="_blank" href="anenst.html">关于我们</a>
                        </li>
                        <li>
                            <a target="_blank" href="secure.html">安全保障</a>
                            <a target="_blank" href="help-center.html">常见问题</a>
                        </li>
                        <li>
                            <a target="_blank" href="Franchise-chain.html">连锁加盟</a>
                            <a target="_blank" href="Franchise-chain.html">合作伙伴</a>
                        </li>
                    </ul>
                </div>
                <div class="foo-two">
                    <p>客服邮箱：kefu@bjdiandaitong.com</p>
                    <p><i class="tel"></i><b>400-050-3015</b></p>
                    <p>工作日：09:00~18:00 - 节假日：09:00~18:00</p>
                </div>
                <div class="foo-three">
                    <p>微信扫一扫</p>
                    <i></i>
                </div>
            </div>
        </div>

        <div class="foo-f">
            <div class="foo-fotr">
                <p>©2015 北京市典贷通信息服务有限公司 京ICP备15026559号 &nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.cnzz.com/stat/website.php?web_id=1255410260" title="站长统计"><em class=""><img src="http://icon.cnzz.com/img/pic.gif" alt=""></em></a></p>
                <p>北京市海淀区上地国际创业园2号院一号楼17层</p>
                <p>市场有风险 投资需谨慎</p>
                <div class="certification">
                    <a href="javascript:;"><i class="cer-1" title="诚信网站"></i></a>
                    <a href="javascript:;"><i class="cer-2" title="互联网金融行业认证"></i></a>
                    <a href="javascript:;"><i class="cer-3" title="行业认证"></i></a>
                    <a href="javascript:;"><i class="cer-4" title="360网站安全监测"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--footer结束-->
<script>
    $(function () {
        $('.recharge-sub').click(function () {
            var money = $('#add').val();
            $.ajax({
                    url:'{% url 'aqq:recharge' %}',
                    type:'POST',
                    data:{money:money,csrfmiddlewaretoken: '{{ csrf_token }}'},
                    success:function (data) {
                    if(data.code==200){
                        $('.recharge').hide();
                        $('.recharge-suss').show();
                        $('#balance').text(data.balance)
                    } else if(data.code==300){alert(data.msg)}
                    else if(data.code==300){alert(data.msg)}
                }
            });

        })
    })
</script>
</body>
</html>

templates/my-withdraw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的账户-提现</title>
    <!--公共样式-->
    <link rel="stylesheet" href="/static/css/global.css">
    <link rel="stylesheet" href="/static/css/my-account.css">
    <script src="/static/js/jquery-1.8.2.js"></script>

    <!--公共js-->
    <script src="/static/js/common.js"></script>
    <script src="/static/js/my-account.js"></script>
</head>
<body>
<!--head开始-->
<div class="head">
    <!--顶头-->
    <div class="top-head">
        <div class="top-menu">
            <!--左边-->
            <div class="top-left">
                <p>客服热线: &nbsp;400-050-3015</p>
                <!--微信二维码-->
                <div class="mobile">
                    <p class="icc" id="wechat">
                        <i class="Wechat"></i>微信
                    </p>
                    <!--二维码-->
                    <div class="wecgat-rq">
                    </div>
                </div>
                <!--QQ客服-->
                <p class="icc"><a href="javascript:;" target="_blank"><i class="QQ"></i>客服</a></p>

            </div>
            <!--右边-->
            {% if user %}
            <div class="top-right">
                <a target="_blank" href="{% url 'aqq:account' %}">您好！{{ user.name }}</a>
                <a target="_blank" href="{% url 'aqq:logout' %}">退出</a>
                <a target="_blank" href="help-center.html">帮助中心</a>
            </div>
            {% else %}
                <div class="top-right">
                <a target="_blank" href="{% url 'aqq:enroll' %}">快速注册</a>
                <a target="_blank" href="{% url 'aqq:login' %}">立即登录</a>
                <a target="_blank" href="help-center.html">帮助中心</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!--LOGO及导航-->
    <div class="top-nav">
        <a href="index.html"><div class="logo"></div></a>
        <div class="nav-list">
            <ul>
                 <li><a target="_blank" href="{% url 'aqq:home' %}">首页</a></li>
                <li><a target="_blank" href="{% url 'aqq:invest' tid=0 sid=0 did=0 page=1 %}">投资理财</a></li>
                <li><a target="_blank" href="{% url 'aqq:borrow' %}" class="red">借贷专区</a></li>
                <li><a target="_blank" href="{% url 'aqq:secure' %}">安全保障</a></li>
                <li><a target="_blank" href="{% url 'aqq:anenst' %}">关于我们</a></li>
                <li><a target="_blank" href="{% url 'aqq:guide' %}">新手引导</a></li>
                <li><a target="_blank" href="{% url 'aqq:account' %}" class="my-cons"><i class="my-con"></i>我的账户</a></li>
            </ul>
        </div>
    </div>

</div>
<!--head结束-->
<div class="bd clearfix">
    <div class="kong"></div>
    <!---->
    <!--面包屑导航-->
    <div class="crumbs" style="background-color:#f3f3f3">
        <span><a href="javascript:;" title="当前位置">当前位置：</a></span>
        <span><a href="{% url 'aqq:home' %}" target="_blank" title="首页">首页</a>&nbsp;&gt;&nbsp;</span>
        <span><a href="{% url 'aqq:account' %}" style="color: #F3270D" target="_blank" title="我的账户">我的账户</a></span>

    </div>
    <div class="center">
        <!--左侧导航-->
        <div class="nav-left">
            <ul class="my-list">
                <li class="my-own nav-one"><i class="accicon-l-1"></i><a href="{% url 'aqq:account' %}">账户首页</a></li>
                <li class="my-own my-fund-1"><i class="accicon-l-2"></i>我的资金 <i class="accicon-r-1"></i></li>
                <div class="my-rec-1">
                    <ul>
                        <li><a href="{% url 'aqq:recharge' %}">充值</a></li>
                        <li><a href="{% url 'aqq:withdraw' %}" class="red">提现</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-2"><i class="accicon-l-3"></i>我的投资 <i class="accicon-r-2"></i></li>
                <div class="my-rec-2">
                    <ul>
                        <li><a href="my-investment.html">投资记录</a></li>
                        <li><a href="my-financing.html">资金记录</a></li>
                        <li><a href="my-drawmoney.html">提现记录</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-3"><i class="accicon-l-4"></i>我的借款 <i class="accicon-r-3"></i></li>
                <div class="my-rec-3">
                    <ul>
                        <li><a href="my-borrowing.html">借款记录</a></li>
                        <li><a href="my-payments.html">回款记录</a></li>
                    </ul>
                </div>
                <li class="my-own my-fund-4"><i class="accicon-l-5"></i>个人设置 <i class="accicon-r-4"></i></li>
                <div class="my-rec-4">
                    <ul>
                        <li><a href="my-setdatum.html">基本信息</a></li>
                        <li><a href="my-setsecure.html">安全中心</a></li>
                    </ul>
                </div>
{#                <li class="my-own"><i class="accicon-l-6"></i> <i class="acc-add"></i><a href="my-invite.html">我的邀请</a></li>#}
{#                <li class="my-own"><i class="accicon-l-7"></i><a href="my-brokerage.html">我的佣金</a></li>#}
            </ul>
        </div>

        <!--右侧内容-->
        <div class="center-box">
            <!--提现-->
            <div class="withdraw">
                <div class="withdraw-txt">
                    <h3><i class="wjx"></i>
                        温馨提示
                    </h3>
                    <p>1. 用户在完成身份认证、开通融托富托管账户、添加银行卡后，才能申请提现；</p>
                    <p>2. 为保障资金安全，每个用户只能绑定1张提现银行卡，如需更换银行卡，请联系典贷通客服并提供相关资料；</p>
                    <p>3. 提现绑卡过程中，若银行卡鉴权失败，请核对您在银行预留的账户资料与在融托富开户时填写的账户资料</p>
                    <p> &nbsp; &nbsp; &nbsp;是否一致（如姓名、身份证号、银行卡号、银行预留手机号）；</p>
                    <p>4. 由于银行结算原因，提现具体到账时间请以银行到账时间为准；</p>
                    <p>5. 提现过程遇到问题请联系在线客服或拨打: 400-050-3015。</p>
                </div>
                <div class="withdraw-num">
                    <ul>
                        <li>
                            <span>账户余额 <em>{{ balance }}</em>元</span>
                        </li>
                        <li>
                            <label>提现金额</label>
                            <input type="text" value="" class="infos" placeholder="请输入提现金额" id="sub"/>
                        </li>
                        <li>
{#                            <a href="javascript:;" class="withdraw-sub">提现</a>#}
                            <button  class="withdraw-sub" id="btn">提现</button>
                        </li>
                    </ul>
                </div>
            </div>
            <!--充值成功-->
            <div class="withdraw-suss">
                <div class="withdraw-prompt">
                    <h3><i></i>提现成功</h3>
                    <span>账户余额 <em id="balance"></em>元</span>
                </div>
            </div>
        </div>

    </div>
</div>
<!--右侧悬浮回到顶部-->
<div class="toolbar" id="rights" style="display: none">
    <a href="javascript:;" class="toolbar-item toolbar-item-weixin">
        <span class="toolbar-layer"></span>
    </a>
    <a href="Feedback.html" class="toolbar-item toolbar-item-feedback"></a>
    <a href="javascript:;" id="returnTop" class="toolbar-item toolbar-item-top"></a>
</div>
<!--footer开始-->
<div class="footer">
    <div class="foo-conter">
        <div class="foo-t">
            <div class="foo-top">
                <div class="foo-one">
                    <ul>
                        <li>
                            <a target="_blank" href="business.html">业务模式</a>
                            <a target="_blank" href="anenst.html">关于我们</a>
                        </li>
                        <li>
                            <a target="_blank" href="secure.html">安全保障</a>
                            <a target="_blank" href="help-center.html">常见问题</a>
                        </li>
                        <li>
                            <a target="_blank" href="Franchise-chain.html">连锁加盟</a>
                            <a target="_blank" href="Franchise-chain.html">合作伙伴</a>
                        </li>
                    </ul>
                </div>
                <div class="foo-two">
                    <p>客服邮箱：kefu@bjdiandaitong.com</p>
                    <p><i class="tel"></i><b>400-050-3015</b></p>
                    <p>工作日：09:00~18:00 - 节假日：09:00~18:00</p>
                </div>
                <div class="foo-three">
                    <p>微信扫一扫</p>
                    <i></i>
                </div>
            </div>
        </div>

        <div class="foo-f">
            <div class="foo-fotr">
                <p>©2015 北京市典贷通信息服务有限公司 京ICP备15026559号 &nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.cnzz.com/stat/website.php?web_id=1255410260" title="站长统计"><em class=""><img src="http://icon.cnzz.com/img/pic.gif" alt=""></em></a></p>
                <p>北京市海淀区上地国际创业园2号院一号楼17层</p>
                <p>市场有风险 投资需谨慎</p>
                <div class="certification">
                    <a href="javascript:;"><i class="cer-1" title="诚信网站"></i></a>
                    <a href="javascript:;"><i class="cer-2" title="互联网金融行业认证"></i></a>
                    <a href="javascript:;"><i class="cer-3" title="行业认证"></i></a>
                    <a href="javascript:;"><i class="cer-4" title="360网站安全监测"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--footer结束-->


{#<script>#}
{#    $(function () {#}
{#        $('.withdraw-sub').click(function () {#}
{#            $('.withdraw').hide();#}
{#            $('.withdraw-suss').show();#}
{#        })#}
{#    })#}
{#</script>#}
</body>
<script>
$(function () {
        $('.withdraw-sub').click(function () {
            var money = $('#sub').val();
            $.ajax({
                    url:'{% url 'aqq:withdraw' %}',
                    type:'POST',
                    data:{money:money,csrfmiddlewaretoken: '{{ csrf_token }}'},
                    success:function (data) {
                    if(data.code==200){
                        $('.withdraw').hide();
                        $('.withdraw-suss').show();
                        $('#balance').text(data.balance)
                    } else if(data.code==300){alert(data.msg)}else if(data.code==400){alert(data.msg)}
                }
            });

        })
    })
        </script>
</html>